### ISSUE TITLE
Date should be displayed as a string after choosing it from Date Picker.

### ISSUE THREAD

**Issue by insfirred** [insfirred/quit-smoking#13]
![dp](https://user-images.githubusercontent.com/90959376/194302689-6cb8f9b2-985c-4be0-91d6-e2e5aa753091.png)
### Suppose we choose 2nd October 2022, then it should be displayed like this
![dp1](https://user-images.githubusercontent.com/90959376/194302695-5bb991b3-d486-4529-9f41-84028a93974e.png)

**Comment by insfirred** [comment]
> Can I work on this task?

ok @sayantan06 , assigning this one to you.

**Comment by sayantan06** [comment]
Sorry, I not really familiar with dart and swift

**Comment by insfirred** [comment]
> Sorry, I not really familiar with dart and swift

okk, but from next time make sure to have complete info about the work you are going to do before asking for assignees.
