### ISSUE TITLE
Timer should be updating in real time.

### ISSUE THREAD

**Issue by insfirred** [insfirred/quit-smoking#14]
Right Now, the time displaying in the timer is hard-coded. The objective of this issue is to make the timer working that is updating in real time.
As soon as the user open the app for the first time, the timer starts from 0 seconds and keeps goings.

![timer](https://user-images.githubusercontent.com/90959376/194309383-1c001ae1-23b8-447e-aa2c-1281ecea88a8.png)

### Refer to [FIGMA FILE](https://www.figma.com/file/AoCnj9cF0chozmdPN2gQPE/I-CAN?node-id=0%3A1) for more info

**Comment by mitf** [comment]
hello @insfirred can u assign this to me

**Comment by insfirred** [comment]
> hello @insfirred can u assign this to me

Already assigned this issue to someone else, if the current assignee didn't complete the issue, then I'll assign this to you, till then you can check my other issues :)

**Comment by suryanshsangwan** [comment]
I am still working on this issue.

**Comment by insfirred** [comment]
@suryanshsangwan , reminder to complete the issue

**Comment by insfirred** [comment]
> I am still working on this issue.

@suryanshsangwan what's the status of your work, if you are not making a Pull request today then I'll assign it to @mitf

**Comment by insfirred** [comment]
@mitf , I'm assigning this issue to you, you can start working on it.

**Comment by insfirred** [comment]
@mitf Thanks for the contribution :)
