### ISSUE TITLE
Greeting message should be displayed according to current time.

### ISSUE THREAD

**Issue by insfirred** [insfirred/quit-smoking#15]
![greetings](https://user-images.githubusercontent.com/90959376/194310000-9a6bd9cc-2964-4ce1-a348-8006c22f7cdd.png)
Right now, This greeting message is hard-coded as Good Evening, have to make it dynamic.
The Greeting message should be displayed according to the current time of the user's device.
### Greeting message convention
- 05:00 AM - 11:59 AM  -> Good Morning
- 12:00 PM - 04:59 PM  -> Good Afternoon
-  05:00 PM - 04:59AM  -> Good Evening

**Comment by Siddhanthota** [comment]
can u assign this to me?

**Comment by manav-06** [comment]
Hi @insfirred You can assign this to me

**Comment by insfirred** [comment]
ok @Siddhanthota assigning this issue to you.

**Comment by insfirred** [comment]
@Siddhanthota , reminder to complete the issue

**Comment by Siddhanthota** [comment]
I am extremely sorry to inform you that I will not be able to devote time as of my current situation. I am unassigning myself so that others can work on this. 

> @Siddhanthota , reminder to complete the issue

**Comment by insfirred** [comment]
> hi @insfirred can you assign me for this issue

Okk @mitf , assigning this one to you
