### ISSUE TITLE
Display a random motivating fact

### ISSUE THREAD

**Issue by insfirred** [insfirred/quit-smoking#16]
Display a random motivating fact that updates everytime in some period of time (like changes in every 30 seconds).
### Suggestions
- Can use any API.
- or Create a list of many motivating facts and fetches them from that list.
![greetings](https://user-images.githubusercontent.com/90959376/194312984-a46eb886-825d-4032-85ba-5bd6ca4d85d0.png)

**Comment by manav-06** [comment]
Hi @insfirred You can assign this to me

**Comment by insfirred** [comment]
> Hi, I would to take up this issue and work on it.

ok @Pauline-wanjiku assigning this one to you.

**Comment by insfirred** [comment]
@Pauline-wanjiku , reminder to complete the issue

**Comment by mitf** [comment]
hi @insfirred can i  take this issue to?

**Comment by insfirred** [comment]
ok @mitf , assigning this one to you

**Comment by mitf** [comment]
I have finished working on this issue, you can check on my PR #32

**Comment by insfirred** [comment]
> I have finished working on this issue, you can check on my PR #32

@mitf , you done amazing work :)
