### ISSUE TITLE
Make Onboarding Screen as One Time Screens that open only once for the first time.

### ISSUE THREAD

**Issue by insfirred** [insfirred/quit-smoking#17]
### You can use Shared Preferences for this implementation.
Onboarding Screens should be displayed only once for the first time start of app.
Then after passing all the onboarding screens, the navigation should go to the HomeScreen.
![nav](https://user-images.githubusercontent.com/90959376/194316400-284637ef-14e7-4635-b918-7c52f355f5b9.png)

**Comment by SwaroopSambhayya** [comment]
Hi, I would like to take up this issue can you assign it to me?

**Comment by insfirred** [comment]
ok @SwaroopSambhayya , assigning this one to you.

**Comment by SwaroopSambhayya** [comment]
Can you give me the permission to push?

**Comment by insfirred** [comment]
> Can you give me the permission to push?

You don't need permissions to contribute, I think you are doing it in a wrong way

**The correct way to contribute**
- First, fork this project
- Clone the forked one
- Resolve the issue 
- Commit the changes
- Push the changes
- Then, open a Pull Request

After that, I'll merge your PR

**Comment by SwaroopSambhayya** [comment]
#19

**Comment by SwaroopSambhayya** [comment]
Pull request has been created

**Comment by insfirred** [comment]
Thanks @SwaroopSambhayya , you done amazing work :)

**Comment by SwaroopSambhayya** [comment]
> Thanks @SwaroopSambhayya , you done amazing work :)

you are welcome! Thanks for the opportunity
