### ISSUE TITLE
Share the progress of the user as a image.

### ISSUE THREAD

**Issue by insfirred** [insfirred/quit-smoking#18]
![share](https://user-images.githubusercontent.com/90959376/194371574-f48d6360-df44-4b0d-b5e9-5681a35541a9.png)
By clicking on share button, user should be able to share his/her progress as a image. 
## Image to be shared should be like this
![imagetobeshared](https://user-images.githubusercontent.com/90959376/194372032-76a64822-8516-4b39-b053-b9f1f3105298.png)

**Comment by abhijeetanand29** [comment]
please assign this issue to me

**Comment by insfirred** [comment]
ok @abhijeetanand29 , assigning this one to you.

**Comment by insfirred** [comment]
@abhijeetanand29 , reminder to complete the issue

**Comment by abhijeetanand29** [comment]
yeah on it

**Comment by stuck-in-a-conundrum** [comment]
@insfirred I can take up this issue if not yet done

**Comment by insfirred** [comment]
> @insfirred I can take up this issue if not yet done

ok @stuck-in-a-conundrum , assigning this to you

**Comment by stuck-in-a-conundrum** [comment]
I have solved this issue in my PR #36
