### ISSUE TITLE
Create Home Screen

### ISSUE THREAD

**Issue by insfirred** [insfirred/quit-smoking#2]
- Develop a home screen for the app as given in the figma file.
- A proper timer should be created that updates in real time.
- The results (like money saved and life saved) should be displayed according to the data input by user in Onboarding Screens, but for now you can hardcode the values.

Refer to Figma file for more info

[Design for the screens](https://www.figma.com/file/AoCnj9cF0chozmdPN2gQPE/I-CAN?node-id=0%3A1)

**Comment by Chaitanya-087** [comment]
hi! i would like to work on this issue

**Comment by insfirred** [comment]
Ok @Chaitanya-087 , Assigning this issue to you.

**Comment by Chaitanya-087** [comment]
sorry i didn't  see it was on flutter

**Comment by ashishmohapatra240** [comment]
Hey, I would like to work on this issue!

**Comment by insfirred** [comment]
ok @ashishmohapatra240 , Assigning this issue to you.
