### ISSUE TITLE
Display the Name on HomeScreen entered by the user in first onboarding screen

### ISSUE THREAD

**Issue by insfirred** [insfirred/quit-smoking#26]
## First OnboardingScreen
<img src="https://user-images.githubusercontent.com/90959376/195159586-0a873259-4cf9-4325-9ee9-334a05f2ed2d.png" alt="ss1" width="200"/>

## HomeScreen
<img src="https://user-images.githubusercontent.com/90959376/195160360-fcb9d5e7-e8e4-4d92-b007-3bee20178286.png" alt="ss1" width="200"/>

Display the name entered by user **_in place if John_** 
Currently, "Good Evening, John" is hard-coded, you have to make it dynamic.

**Comment by insfirred** [comment]
> pls assign

ok @pratikagr , assigning this one to you.

**Comment by mitf** [comment]
hi @insfirred can i take this one if not done yet

**Comment by mitf** [comment]
i done with this issue you can review in my pr #35
