### ISSUE TITLE
Change the Icon of the app for Android and IOS.

### ISSUE THREAD

**Issue by insfirred** [insfirred/quit-smoking#27]
### Change the App Icon for Android as well as IOS, Currently the app icon is the default icon provided by flutter

**Comment by Frey0-0** [comment]
I would like to work on this issue @insfirred

**Comment by insfirred** [comment]
> I would like to work on this issue @insfirred

ok @Frey0-0 , assigning this one to you. Please find the attached icon in the given drive link. 
**_Note: I just updated the icon few minutes ago, please use the updated one_**
