### ISSUE TITLE
Update the Money Saved every minute according to the formula.

### ISSUE THREAD

**Issue by insfirred** [insfirred/quit-smoking#37]
### In the onboarding screens, User enters some data 
- His Name
- Number of cigarettes smoked per day
- Number of cigarettes in one pack
- Cost of a pack

## Timer in Home Screen is updating every second, you have to calculate the money saved according to timer.
- First calculate the money saved by user per minute (it could be in decimal).
- Update it in real time
![HomeScreen](https://user-images.githubusercontent.com/90959376/197380152-5e0f95a4-f25e-4356-92a8-2a9562b592df.png)

**Comment by Tanmai2002** [comment]
I am working on this one
