### ISSUE TITLE
Update the Cigarette saved till now (It should be updating in real time)

### ISSUE THREAD

**Issue by insfirred** [insfirred/quit-smoking#38]
### In the onboarding screens, User enters some data 
- His Name
- Number of cigarettes smoked per day
- Number of cigarettes in one pack
- Cost of a pack

## Timer in Home Screen is updating every second, you have to calculate the cigarette saved according to timer.
- First calculate the number of cigarette smoked by user per minute (it could be in decimal).
- Update it in real time
![HomeScreen](https://user-images.githubusercontent.com/90959376/197380619-2fe31005-1221-4c60-a6ff-9f0282bd72a5.png)

**Comment by Ishikasaraf20** [comment]
hey @insfirred can you assign this issue to me i can work on it

**Comment by insfirred** [comment]
Ok @Ishikasaraf20 , assigning this one to you.
